/* Generated By:JavaCC: Do not edit this line. compConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TIPOS = 5;
  /** RegularExpression Id. */
  int NUMERO = 6;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 7;
  /** RegularExpression Id. */
  int CADEIA = 8;
  /** RegularExpression Id. */
  int IGUAL = 9;
  /** RegularExpression Id. */
  int MAIS = 10;
  /** RegularExpression Id. */
  int MENOS = 11;
  /** RegularExpression Id. */
  int MULTIPLICAR = 12;
  /** RegularExpression Id. */
  int DIVIDIR = 13;
  /** RegularExpression Id. */
  int INCR = 14;
  /** RegularExpression Id. */
  int DECR = 15;
  /** RegularExpression Id. */
  int MAIN = 16;
  /** RegularExpression Id. */
  int PROGRAMA = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int ELSEIF = 20;
  /** RegularExpression Id. */
  int FOR = 21;
  /** RegularExpression Id. */
  int SWITCH = 22;
  /** RegularExpression Id. */
  int CASE = 23;
  /** RegularExpression Id. */
  int BREAK = 24;
  /** RegularExpression Id. */
  int DEFAUL = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int WRITE = 28;
  /** RegularExpression Id. */
  int READ = 29;
  /** RegularExpression Id. */
  int EPARENTESE = 30;
  /** RegularExpression Id. */
  int DPARENTESE = 31;
  /** RegularExpression Id. */
  int ECHAVE = 32;
  /** RegularExpression Id. */
  int DCHAVE = 33;
  /** RegularExpression Id. */
  int ECOLCHETE = 34;
  /** RegularExpression Id. */
  int DCOLCHETE = 35;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 36;
  /** RegularExpression Id. */
  int VIRGULA = 37;
  /** RegularExpression Id. */
  int PONTO = 38;
  /** RegularExpression Id. */
  int IGUALIGUAL = 39;
  /** RegularExpression Id. */
  int MENORIGUAL = 40;
  /** RegularExpression Id. */
  int MAIORIGUAL = 41;
  /** RegularExpression Id. */
  int DIFERENTE = 42;
  /** RegularExpression Id. */
  int OR = 43;
  /** RegularExpression Id. */
  int AND = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<TIPOS>",
    "<NUMERO>",
    "<IDENTIFICADOR>",
    "<CADEIA>",
    "\"= \"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"++\"",
    "\"--\"",
    "\"public static void Main() \"",
    "\"Programa \"",
    "\"if \"",
    "\"else \"",
    "\"elseif \"",
    "\"for \"",
    "\"switch \"",
    "\"case \"",
    "\"break \"",
    "\"default \"",
    "\"do \"",
    "\"while \"",
    "\"write \"",
    "\"read \"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
  };

}
